apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-umbrella-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Crystalzord/argocd-poc.git'
    targetRevision: HEAD
    path: applications-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true