apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-three
spec:
  selector:
    matchLabels:
      app: nginx-three
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: nginx-three
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image.repository }}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi