apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-one-argo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Crystalzord/argocd-poc.git'
    targetRevision: HEAD
    path: app1
    helm:
      valueFiles:
      - values_dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true